### ISSUE TITLE
Variable Expansion not Working

### ISSUE THREAD

**Issue by posborne** [bahdotsh/wrkflw#11]
In this snippet of a workflow (from https://github.com/posborne/sightglass/blob/update-ci/.github/workflows/benchmarks.yml)

```
  build-wasmtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # for now, limit this a bit
        revision: ["main", "v25.0.0"]
    env:
      REVISION: ${{ matrix.revision }}
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - name: Build Engine
      run: |
        pushd engines/wasmtime
        rustc build.rs
        ./build
        popd
    - name: Upload Wasmtime Shared Library
      uses: actions/upload-artifact@v4
      with:
        name: wasmtime-${{ matrix.revision }}
        path: engines/wasmtime/libengine.so
```

It would appear that variable expansion using `${{ <var> }}` is not working.  The ENV var defined ends up including the string "${{ matrix.revision }}" which results in build failures locally.
