### ISSUE TITLE
Support for Reusing Workflows (uses: syntax)

### ISSUE THREAD

**Issue by matsuu** [bahdotsh/wrkflw#18]
When using the GitHub Actions [Reusing workflows](https://docs.github.com/en/actions/sharing-automations/reusing-workflows) feature, it is possible to define jobs using the uses: keyword as shown below:

```yaml
# (snip)
jobs:
  call-workflow-1-in-local-repo:
    uses: octo-org/this-repo/.github/workflows/workflow-1.yml@172239021f7ba04fe7327647b213799853a9eb89
```

However, when running `wrkflw validate` on a file containing jobs defined this way, it outputs the following errors:

```
❌ Invalid: .github/workflows/foo.yml
   1. Workflow is missing a name
   2. Job 'call-workflow-1-in-local-repo' is missing 'runs-on' field
   3. Job 'call-workflow-1-in-local-repo' is missing 'steps' section
```
