### ISSUE TITLE
Failed to parse workflow structure: invalid type: string "changes", expected a sequence at 1

### ISSUE THREAD

**Issue by elfenpiff** [bahdotsh/wrkflw#20]
This is a great tool, and I can't wait to use it in my development workflow!

In this snippet of the workflow taken from our project (https://github.com/eclipse-iceoryx/iceoryx2/blob/main/.github/workflows/build-test.yml)

```yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release* ]
    types: [ opened, ready_for_review, reopened, synchronize ]

# env:
  # RUSTFLAGS: "-C debug-assertions"

jobs:

  changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      source-code: ${{ steps.filter.outputs.source-code }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Check for changed file types
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # ratchet:dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            source-code:
              - '!**/*.md'
            markdown:
              - '**/*.md'

# ...
```

it seems that wrkflw cannot parse `changes`. We use it to run only the runners we actually require for a pull request - so if there are no source code changes, just markdown changes, we do not need to build and run unit tests.
