### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bahdotsh** [bahdotsh/wrkflw#7]
• Next steps don't continue if I start a process in the background (in a job step) e.g. my-command &
(It also doesn't clean up the process, if I cancel the TUI)
• `bash: line 2: $GITHUB_OUTPUT: ambiguous redirect`
(regarding the following line in my workflow: echo `"links=$links" >> $GITHUB_OUTPUT)`
Though I can probably modify the job, so it doesn't use gh variables

First TUI review (maybe you have already planned some stuff for those though):

• How do I change the default runtime (to use emulation mode in the TUI by default)?
Oh, when you use `wrkflw tui -e it `works.
Still, how do I change this inside the tui?
• The tabs have marked the first letter, but this works only for the Help page.
(1-4 for the tabs work as described in the help page, so no real issue, just a bit confusing)
• The jobs can only be inspected when they are completed already.
• How do I get the full log for a single step? I can make my terminal higher, to see more output details, but my screen isn't infinitely high
• How do I move to and in the output area for a step to see its full logs?

**Comment by bahdotsh** [comment]
Hey @nobkd, I have made some improvements and have also updated the readme with the updates. It'd be cool if you could check it out and give me some feedback when you find time!

**Comment by nobkd** [comment]
Hey, thank you.
- I still don't know how to scroll in the log view for a job step
- I experience the following issue:

Crafted file:
```yaml
# .github/workflows/test.yaml
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Hey
        run: |
          echo hello && echo world
```

![Image](https://github.com/user-attachments/assets/978a6eb1-869c-46f3-9a22-ecda8f104ed4)

Thanks for your hard work. I'll add more comments, if I find more!
